language: python
python:
- '2.7'
sudo: false
env:
- DB=sqlite3
- DB=postgres
install:
- pip install . --no-deps
- pip install --use-mirrors --no-deps -r test_project/requirements.txt
- if [ $DB == 'postgres' ]; then pip install --use-mirrors --no-deps psycopg2==2.5.3;
  fi
before_script:
- if [ $DB == 'postgres' ]; then psql -c 'drop database if exists brambling_test;'
  -U postgres; fi
- if [ $DB == 'postgres' ]; then psql -c 'create database brambling_test;' -U postgres;
  fi
script:
- cd test_project
- "./manage.py test --verbosity=2 brambling"
notifications:
  slack:
    secure: U8uCS43H0wmkkolDc2VLdwN+vJTxfZtjP/1tHKejUGD6BKWJ5uKBjUjZFpy4O8FcfKkpybSobkK9bgo8/5UV9fi01/Ybli5oBp6gBQARQUKtzFBzLtSGReD5QHa/ezFcoFlxHkCFOZe4oZc/C2+l/x8IyaXxeB3pQvlFeKP+PSw=
    on_success: change
    on_failure: always
    on_start: never
